var texts = [
    "Using the SVG format, output a schematic drawing of a smiley face. Put the output in the code block.",
    "keep the circular face, but don't fill it with the yellow",
    "this is great! can you make the outer circle black instead of yellow ?",
    "okay, now can you change the eyes to squares instead of circles.",
    "make the square eyes bigger, and make them hollow",
    "put the eyes further apart, and symmetrical across the face",
    "move the square on the right side a bit left so it doesn't go outside the face",
    "move it a bit more toward left",
    "this is great! now make the left eye a bit toward the left as well",
    "make both eyes smaller, about 70% of the original size",
    "move the left square more left, and move the right square more right again",
    "let's work on the mouth, can you change the mouth into just a semi-circle?",
    "that didn't quite work. can you remove the mouth ?",
    "let's draw the mouth one part at the time. the first is a horizontal line in the middle of the face",
    "make the line thinner, lower, and longer",
    "move the line lower",
    "move the line in the opposite direction",
    "this is really good! add a new arc below the line, forming the mouth",
    "make the arc thinner",
    "make the arc bigger",
    "perfect! move the arc down a little bit",
    "move it up a little little bit",
    "move up a tiny tiny bit again",
    "make the mouth thinner in width",
    "undo the last change",
    "make the stroke width of the mouth thinner",
    "make the stroke width of the line thinner as well",
    "make the line a bit lower",
    "make the outer circle thinner in stroke width",
    "make the eyes bit further apart",
    "move the eyes down a little bit",
    "move the eyes up",
    "make all the stroke width a tiny bit thinner",
    "bit thinner again",

]